<?php
/**
 * Title: Complete editable homepage
 * Slug: feast-middle-east/homepage
 * Categories: feast, featured
 * Description: The catering-first homepage built from editable core blocks.
 * Viewport Width: 1440
 */
$img = static function ( $file ) {
	return esc_url( get_template_directory_uri() . '/assets/images/' . $file );
};
?>
<!-- wp:group {"tagName":"main","className":"feast-native-home","layout":{"type":"default"}} -->
<main class="wp-block-group feast-native-home" id="main-content">
<!-- wp:group {"tagName":"section","className":"hero feast-native-slider","layout":{"type":"default"}} -->
<section class="wp-block-group hero feast-native-slider">
<!-- wp:cover {"url":"<?php echo $img( 'hero-catering-spread.jpg' ); ?>","dimRatio":60,"overlayColor":"forest","minHeight":70,"minHeightUnit":"vh","contentPosition":"center left","className":"hero-slide is-active","layout":{"type":"constrained"}} -->
<div class="wp-block-cover has-custom-content-position is-position-center-left hero-slide is-active" style="min-height:70vh"><span aria-hidden="true" class="wp-block-cover__background has-forest-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="A generous Middle Eastern catering spread" src="<?php echo $img( 'hero-catering-spread.jpg' ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"hero-copy","layout":{"type":"constrained","justifyContent":"left"}} --><div class="wp-block-group hero-copy"><!-- wp:paragraph {"className":"eyebrow eyebrow--light"} --><p class="eyebrow eyebrow--light">Middle Eastern catering across Sydney</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">A feast worth gathering for.</h1><!-- /wp:heading --><!-- wp:paragraph {"className":"hero-lead"} --><p class="hero-lead">Generous, traditional food for weddings, work lunches, family celebrations and everything in between.</p><!-- /wp:paragraph --><!-- wp:buttons {"className":"hero-actions"} --><div class="wp-block-buttons hero-actions"><!-- wp:button {"backgroundColor":"cream","textColor":"forest"} --><div class="wp-block-button"><a class="wp-block-button__link has-forest-color has-cream-background-color has-text-color has-background wp-element-button" href="#catering-enquiry">Request a catering quote</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#catering">Explore catering</a></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:paragraph {"className":"hero-note"} --><p class="hero-note">Freshly prepared in Granville</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div>
<!-- /wp:cover -->
<!-- wp:cover {"url":"<?php echo $img( 'hero-chicken-mansaf.jpg' ); ?>","dimRatio":60,"overlayColor":"forest","minHeight":70,"minHeightUnit":"vh","contentPosition":"center left","className":"hero-slide","layout":{"type":"constrained"}} -->
<div class="wp-block-cover has-custom-content-position is-position-center-left hero-slide" style="min-height:70vh"><span aria-hidden="true" class="wp-block-cover__background has-forest-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Chicken mansaf prepared for sharing" src="<?php echo $img( 'hero-chicken-mansaf.jpg' ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"hero-copy","layout":{"type":"constrained","justifyContent":"left"}} --><div class="wp-block-group hero-copy"><!-- wp:paragraph {"className":"eyebrow eyebrow--light"} --><p class="eyebrow eyebrow--light">The family feast</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Big tables. Full plates. Happy people.</h1><!-- /wp:heading --><!-- wp:paragraph {"className":"hero-lead"} --><p class="hero-lead">Build a share-style feast with hot mains, fresh salads, sides and sweets, made to suit your gathering.</p><!-- /wp:paragraph --><!-- wp:buttons {"className":"hero-actions"} --><div class="wp-block-buttons hero-actions"><!-- wp:button {"backgroundColor":"cream","textColor":"forest"} --><div class="wp-block-button"><a class="wp-block-button__link has-forest-color has-cream-background-color has-text-color has-background wp-element-button" href="#catering-enquiry">Build your feast</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#menu">See menu favourites</a></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:paragraph {"className":"hero-note"} --><p class="hero-note">Custom menus for 10–100+ guests</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div>
<!-- /wp:cover -->
<!-- wp:cover {"url":"<?php echo $img( 'hero-event-table.jpg' ); ?>","dimRatio":60,"overlayColor":"forest","minHeight":70,"minHeightUnit":"vh","contentPosition":"center left","className":"hero-slide","layout":{"type":"constrained"}} -->
<div class="wp-block-cover has-custom-content-position is-position-center-left hero-slide" style="min-height:70vh"><span aria-hidden="true" class="wp-block-cover__background has-forest-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="A colourful catered event table" src="<?php echo $img( 'hero-event-table.jpg' ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"hero-copy","layout":{"type":"constrained","justifyContent":"left"}} --><div class="wp-block-group hero-copy"><!-- wp:paragraph {"className":"eyebrow eyebrow--light"} --><p class="eyebrow eyebrow--light">Office &amp; event catering</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Your next event, beautifully fed.</h1><!-- /wp:heading --><!-- wp:paragraph {"className":"hero-lead"} --><p class="hero-lead">From team lunches to milestone celebrations, tell us your guest count and we’ll help plan the food.</p><!-- /wp:paragraph --><!-- wp:buttons {"className":"hero-actions"} --><div class="wp-block-buttons hero-actions"><!-- wp:button {"backgroundColor":"cream","textColor":"forest"} --><div class="wp-block-button"><a class="wp-block-button__link has-forest-color has-cream-background-color has-text-color has-background wp-element-button" href="#catering-enquiry">Cater my event</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="tel:+61407495908">Call 0407 495 908</a></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:paragraph {"className":"hero-note"} --><p class="hero-note">Pickup and delivery options available</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div>
<!-- /wp:cover -->
</section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"catering","backgroundColor":"cream","className":"section","layout":{"type":"constrained"}} -->
<section id="catering" class="wp-block-group section has-cream-background-color has-background"><!-- wp:columns {"verticalAlignment":"bottom","className":"section-heading"} --><div class="wp-block-columns are-vertically-aligned-bottom section-heading"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Catering made simple</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Choose your kind of feast.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"lead"} --><p class="lead">Flexible packages for homes, offices and celebrations. Every menu can be adjusted to your guests and occasion.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"bundle-grid"} --><div class="wp-block-columns bundle-grid">
<!-- wp:column {"className":"bundle-card"} --><div class="wp-block-column bundle-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"bundle-card__image"} --><figure class="wp-block-image size-large bundle-card__image"><img src="<?php echo $img( 'hero-chicken-mansaf.jpg' ); ?>" alt="Family-style chicken mansaf feast"/></figure><!-- /wp:image --><!-- wp:group {"className":"bundle-card__content"} --><div class="wp-block-group bundle-card__content"><!-- wp:paragraph {"className":"bundle-tag"} --><p class="bundle-tag">Warm &amp; generous</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Family Table</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"bundle-for"} --><p class="bundle-for">Ideal for 10–25 guests</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>Choice of hearty mains</li><li>Fresh salads and traditional sides</li><li>Share-style trays, ready for the table</li></ul><!-- /wp:list --><!-- wp:paragraph {"className":"text-link"} --><p class="text-link"><a href="#catering-enquiry">Ask about this feast →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column {"className":"bundle-card bundle-card--featured"} --><div class="wp-block-column bundle-card bundle-card--featured"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"bundle-card__image"} --><figure class="wp-block-image size-large bundle-card__image"><img src="<?php echo $img( 'hero-event-table.jpg' ); ?>" alt="Middle Eastern celebration feast"/></figure><!-- /wp:image --><!-- wp:group {"className":"bundle-card__content"} --><div class="wp-block-group bundle-card__content"><!-- wp:paragraph {"className":"bundle-tag"} --><p class="bundle-tag">Most popular</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Celebration Feast</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"bundle-for"} --><p class="bundle-for">Ideal for 25–100+ guests</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>A generous mix of mains and favourites</li><li>Salads, dips, sides and finger food</li><li>Designed for weddings and big occasions</li></ul><!-- /wp:list --><!-- wp:paragraph {"className":"text-link"} --><p class="text-link"><a href="#catering-enquiry">Plan my celebration →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column {"className":"bundle-card"} --><div class="wp-block-column bundle-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"bundle-card__image"} --><figure class="wp-block-image size-large bundle-card__image"><img src="<?php echo $img( 'menu-wrap.jpg' ); ?>" alt="Fresh wraps for an office lunch"/></figure><!-- /wp:image --><!-- wp:group {"className":"bundle-card__content"} --><div class="wp-block-group bundle-card__content"><!-- wp:paragraph {"className":"bundle-tag"} --><p class="bundle-tag">Easy crowd-pleaser</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Office Lunch</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"bundle-for"} --><p class="bundle-for">Ideal for teams of 10+</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>Easy-to-serve hot mains or wraps</li><li>Fresh salads, dips and sides</li><li>Pickup and delivery options</li></ul><!-- /wp:list --><!-- wp:paragraph {"className":"text-link"} --><p class="text-link"><a href="#catering-enquiry">Feed the team →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"reviews","className":"section reviews-section","layout":{"type":"constrained"}} --><section id="reviews" class="wp-block-group section reviews-section"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Loved around Sydney</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">What our guests say.</h2><!-- /wp:heading --><!-- wp:shortcode -->[trustindex no-registration=google]<!-- /wp:shortcode --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"menu","className":"section","layout":{"type":"constrained"}} --><section id="menu" class="wp-block-group section"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">From our kitchen</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Food made for sharing.</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"lead"} --><p class="lead">Traditional favourites, bright salads and generous mains—prepared fresh in Granville.</p><!-- /wp:paragraph -->
<!-- wp:columns {"className":"menu-showcase"} --><div class="wp-block-columns menu-showcase"><!-- wp:column {"className":"dish-card"} --><div class="wp-block-column dish-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'menu-malfouf.jpg' ); ?>" alt="Traditional malfouf"/></figure><!-- /wp:image --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Malfouf</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Tender stuffed cabbage rolls, slow-cooked and deeply comforting.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"dish-card"} --><div class="wp-block-column dish-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'menu-fattoush.jpg' ); ?>" alt="Fresh fattoush salad"/></figure><!-- /wp:image --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Fresh salads</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Bright, crisp and made to balance every feast.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"dish-card"} --><div class="wp-block-column dish-card"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'menu-warak-enab.jpg' ); ?>" alt="Hand-rolled warak enab"/></figure><!-- /wp:image --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Warak Enab</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Stuffed vine leaves, rolled by hand and full of flavour.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"menu-list"} --><div class="wp-block-columns menu-list"><!-- wp:column {"className":"menu-group"} --><div class="wp-block-column menu-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Hearty mains</h3><!-- /wp:heading --><!-- wp:list --><ul><li>Chicken mansaf</li><li>Malfouf</li><li>Dawood basha</li><li>Seasonal rice dishes</li></ul><!-- /wp:list --></div><!-- /wp:column --><!-- wp:column {"className":"menu-group"} --><div class="wp-block-column menu-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Salads &amp; sides</h3><!-- /wp:heading --><!-- wp:list --><ul><li>Fattoush</li><li>Tabouli</li><li>Hummus</li><li>Batata harra</li></ul><!-- /wp:list --></div><!-- /wp:column --><!-- wp:column {"className":"menu-group"} --><div class="wp-block-column menu-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Bites &amp; extras</h3><!-- /wp:heading --><!-- wp:list --><ul><li>Kibbeh</li><li>Sambousek</li><li>Stuffed vine leaves</li><li>Fresh wraps</li></ul><!-- /wp:list --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/menu/">View the full menu</a></div><!-- /wp:button --></div><!-- /wp:buttons --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","backgroundColor":"forest","textColor":"cream","className":"section process","layout":{"type":"constrained"}} --><section class="wp-block-group section process has-cream-color has-forest-background-color has-text-color has-background"><!-- wp:paragraph {"className":"eyebrow eyebrow--light"} --><p class="eyebrow eyebrow--light">Catering made simple</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Tell us. Choose. Feast.</h2><!-- /wp:heading --><!-- wp:columns {"className":"steps"} --><div class="wp-block-columns steps"><!-- wp:column {"className":"step"} --><div class="wp-block-column step"><!-- wp:paragraph {"className":"step__number"} --><p class="step__number">01</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Tell us the occasion</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Share your date, guest count and what you are planning.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"step"} --><div class="wp-block-column step"><!-- wp:paragraph {"className":"step__number"} --><p class="step__number">02</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Choose your menu</h3><!-- /wp:heading --><!-- wp:paragraph --><p>We will help shape a generous menu around your guests.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"step"} --><div class="wp-block-column step"><!-- wp:paragraph {"className":"step__number"} --><p class="step__number">03</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Gather and feast</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Collect or arrange delivery, then enjoy the table together.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"our-story","className":"section","layout":{"type":"constrained"}} --><section id="our-story" class="wp-block-group section"><!-- wp:columns {"verticalAlignment":"center","className":"story-grid"} --><div class="wp-block-columns are-vertically-aligned-center story-grid"><!-- wp:column {"className":"story-image"} --><div class="wp-block-column story-image"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'owner-kitchen.jpg' ); ?>" alt="Preparing food in the Feast kitchen"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column {"className":"story-copy"} --><div class="wp-block-column story-copy"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Our story</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Food with heart, heritage and generosity.</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"lead"} --><p class="lead">Feast in the Middle East brings the warmth of a family table to gatherings across Sydney.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Our dishes are prepared with traditional flavours, fresh ingredients and the kind of generosity that makes every guest feel welcome.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/our-story/">Meet Feast</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"gallery","backgroundColor":"cream","className":"section","layout":{"type":"constrained"}} --><section id="gallery" class="wp-block-group section has-cream-background-color has-background"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Fresh from Feast</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">A look inside our kitchen.</h2><!-- /wp:heading --><!-- wp:gallery {"linkTo":"none","className":"gallery-grid"} --><figure class="wp-block-gallery has-nested-images columns-default is-cropped gallery-grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'catering-selection.jpg' ); ?>" alt="A selection of catered dishes"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'menu-wrap.jpg' ); ?>" alt="A freshly prepared wrap"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'event-salads.jpg' ); ?>" alt="Colourful event salads"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="<?php echo $img( 'hero-event-table.jpg' ); ?>" alt="A catered celebration table"/></figure><!-- /wp:image --></figure><!-- /wp:gallery --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"catering-enquiry","className":"section enquiry","layout":{"type":"constrained"}} --><section id="catering-enquiry" class="wp-block-group section enquiry"><!-- wp:columns {"verticalAlignment":"center","className":"enquiry-grid"} --><div class="wp-block-columns are-vertically-aligned-center enquiry-grid"><!-- wp:column {"className":"enquiry-copy"} --><div class="wp-block-column enquiry-copy"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">Let’s plan your feast</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Tell us what you are celebrating.</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"lead"} --><p class="lead">Share a few details and we will help build the right menu for your guests and budget.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="tel:+61407495908">Call 0407 495 908</a><br>Inside HAWA Food Spot, 43 South St, Granville NSW</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:shortcode -->[feast_enquiry_form]<!-- /wp:shortcode --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
</main><!-- /wp:group -->
