<?php
/**
 * Title: Editable menu page
 * Slug: feast-middle-east/page-menu
 * Categories: feast
 */
$img = static function ( $file ) { return esc_url( get_template_directory_uri() . '/assets/images/' . $file ); };
?>
<!-- wp:group {"className":"feast-native-page","layout":{"type":"default"}} --><div class="wp-block-group feast-native-page"><!-- wp:cover {"url":"<?php echo $img( 'menu-malfouf.jpg' ); ?>","dimRatio":60,"overlayColor":"ink","minHeight":620,"contentPosition":"bottom left","className":"inner-hero-block","layout":{"type":"constrained"}} --><div class="wp-block-cover has-custom-content-position is-position-bottom-left inner-hero-block" style="min-height:620px"><span aria-hidden="true" class="wp-block-cover__background has-ink-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Traditional Middle Eastern dishes" src="<?php echo $img( 'menu-malfouf.jpg' ); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"className":"eyebrow eyebrow--light"} --><p class="eyebrow eyebrow--light">Traditional flavours</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Our menu</h1><!-- /wp:heading --><!-- wp:paragraph {"className":"lead"} --><p class="lead">Generous Middle Eastern favourites, made fresh for your table or event.</p><!-- /wp:paragraph --></div></div><!-- /wp:cover --><!-- wp:group {"className":"section","layout":{"type":"constrained"}} --><div class="wp-block-group section"><!-- wp:paragraph {"className":"eyebrow"} --><p class="eyebrow">From our kitchen</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Food made for sharing</h2><!-- /wp:heading --><!-- wp:columns {"className":"menu-list"} --><div class="wp-block-columns menu-list"><!-- wp:column {"className":"menu-group"} --><div class="wp-block-column menu-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Hearty mains</h3><!-- /wp:heading --><!-- wp:list --><ul><li>Chicken Mansaf</li><li>Malfouf</li><li>Dawood Basha</li><li>Seasonal rice dishes</li></ul><!-- /wp:list --></div><!-- /wp:column --><!-- wp:column {"className":"menu-group"} --><div class="wp-block-column menu-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Salads &amp; sides</h3><!-- /wp:heading --><!-- wp:list --><ul><li>Fattoush</li><li>Tabouli</li><li>Hummus</li><li>Batata Harra</li></ul><!-- /wp:list --></div><!-- /wp:column --><!-- wp:column {"className":"menu-group"} --><div class="wp-block-column menu-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Bites &amp; extras</h3><!-- /wp:heading --><!-- wp:list --><ul><li>Kibbeh</li><li>Sambousek</li><li>Warak Enab</li><li>Fresh wraps</li></ul><!-- /wp:list --></div><!-- /wp:column --></div><!-- /wp:columns --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/contact/">Ask for catering prices</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group -->
